//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int PartyID { get; set; }
        public string PartyCode { get; set; }
        public int SuperStockistID { get; set; }
        public Nullable<int> PartyGroupID { get; set; }
        public string Party { get; set; }
        public string ShortName { get; set; }
        public string PartyType { get; set; }
        public Nullable<int> PartyTypeId { get; set; }
        public string VendorCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PaymentTermID { get; set; }
        public Nullable<int> DeliveryTermID { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> Editedby { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<int> PriceGroupID { get; set; }
        public Nullable<bool> IsUnregisteredforGST { get; set; }
        public Nullable<bool> IsForeignParty { get; set; }
        public string GSTNo { get; set; }
        public Nullable<System.DateTime> GSTEffectiveDate { get; set; }
        public string PANNO { get; set; }
        public Nullable<System.DateTime> PANNoEffectiveDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string SalesPerson { get; set; }
        public Nullable<bool> IsPurchaseReturnParty { get; set; }
        public string Transporter { get; set; }
        public string TransporterGST { get; set; }
        public Nullable<int> FreightId { get; set; }
        public Nullable<int> CreditDays { get; set; }
    }
}
